FROM node:20-alpine AS base
WORKDIR /app
COPY package.json pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/web ./apps/web
RUN corepack enable
RUN pnpm install --frozen-lockfile
CMD ["pnpm", "--filter", "web", "run", "dev"]
