FROM node:20-alpine AS base
WORKDIR /app
COPY package.json pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/server ./apps/server
COPY packages/shared ./packages/shared
RUN corepack enable
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @acme/shared build
RUN pnpm --filter server build
CMD ["pnpm", "--filter", "server", "run", "dev"]
